Exercicies for conditionals, loops and whiles done!
nilete22/JavaScript-foundations-challenge-1 pull request #5
Opened 2023-11-02 19:50 UTC by nilete22

2023-11-05 17:37 UTC, tictools requested changes

2023-11-05 17:37 UTC, tictools commented on challenge-03_loops-conditionals/loops-conditionals/conditionals/exercise_00.js
> +if (animal === "cat") {
⚠️ FIX: Change animal to different values to make sure it works in all cases

2023-11-05 17:37 UTC, tictools commented on challenge-03_loops-conditionals/loops-conditionals/conditionals/exercise_01.js
> +if (number % 2 === 0) {
⚠️ FIX: Change the variable to test it works for different cases. Print result.

2023-11-05 17:37 UTC, tictools commented on challenge-03_loops-conditionals/loops-conditionals/loops/exercise_02.js
> +for (let i = 1; i <= 100; i++) {
This is the output of your script...
```
Checkpoint! 10
Checkpoint! 20
Checkpoint! 30
Checkpoint! 40
Checkpoint! 50
Checkpoint! 60
Checkpoint! 70
Checkpoint! 80
Checkpoint! 90
Checkpoint! 100
All, done!
```

...have you tested it before pushing? 🤔

⚠️ FIX: needs work.

2023-11-05 17:37 UTC, tictools commented on challenge-03_loops-conditionals/loops-conditionals/while/exercise_01.js
> +while (evenNumber <= 40) {
These loops should iterate over all numbers in between 10 and 40, printing only the odd/even ones, depending on its own logic.

⚠️ FIX: iterate over all numbers and print only the odd/even ones

2023-11-05 17:37 UTC, tictools commented on challenge-03_loops-conditionals/loops-conditionals/while/exercise_02.js
> +let i = 1;
You should take in account what `i` variable is storing. Is this variable referring to any index in this case?

⚠️ FIX: rename properly `i` variable

This is the output of your script...
```
Checkpoint! 10
Checkpoint! 20
Checkpoint! 30
Checkpoint! 40
Checkpoint! 50
Checkpoint! 60
Checkpoint! 70
Checkpoint! 80
Checkpoint! 90
Checkpoint! 100
All, done!
```

...have you tested it before pushing? 🤔

⚠️ FIX: needs work.

2023-11-05 17:37 UTC, tictools commented on challenge-03_loops-conditionals/loops-conditionals/conditionals/exercise_02.js
> +*/
FIX: format code.

2023-11-12 13:29 UTC, tictools requested changes

2023-11-12 13:29 UTC, tictools commented on .githubworkflows/Pipeline.yaml
Actions path is `.github/workflows/Pipeline.yaml`, not `.githubworkflows/Pipeline.yaml`.

No action will be executed until you fix this path.

FIX: write correct path

2023-11-12 16:27 UTC, tictools approved these changes

2023-11-13 17:40 UTC, Lye-Frozen-Heart approved these changes

2023-11-13 17:40 UTC, merged